language: node_js

node_js:
  - '0.12'

compiler: clang

before_install:
  - sudo apt-get update
  - sudo apt-get install --force-yes libcv-dev libcvaux-dev libhighgui-dev libopencv-dev libleptonica-dev libtesseract-dev libzbar-dev
  # put local node-pre-gyp on PATH
  - export PATH=./node_modules/.bin/:$PATH
  # install node-pre-gyp so it is available for packaging and publishing
  - npm install node-gyp -g
  # install node-pre-gyp so it is available for packaging and publishing
  - npm install node-pre-gyp

install:
  # ensure source install works
  - npm install --build-from-source
  # test our module
  - node bin/ocrservice

before_script:

script:

after_success:
